### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by CoderOwl** [goldsmith/Wikipedia#130]
```
$ print wikipedia.summary("Wikipedia")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wikipedia/util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "wikipedia/wikipedia.py", line 231, in summary
    page_info = page(title, auto_suggest=auto_suggest, redirect=redirect)
  File "wikipedia/wikipedia.py", line 270, in page
    results, suggestion = search(title, results=1, suggestion=True)
  File "wikipedia/util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "wikipedia/wikipedia.py", line 103, in search
    raw_results = _wiki_request(search_params)
  File "wikipedia/wikipedia.py", line 742, in _wiki_request
    return r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by rajeshneti98** [comment]
Hi,
   Did someone give a fix to this problem?
