### ISSUE TITLE
wikipedia error: Failed to establish a new connection: [Errno 101] Network is unreachable',))

### ISSUE THREAD

**Issue by happyjin** [goldsmith/Wikipedia#143]
Hi:
I am calling wikipedia.page in the loop of my program. But I fail to do it after a few iterations.
Here is my routine when I call it.

for item in match_artists:
    try:
        #try to load the wikipedia page
        item_first = wikipedia.page(item[0])  ###This is line 47
        item_sec = wikipedia.page(item[1])
        if item_first == item_sec:
            print item
            print "True"
            wiki_true_list.append(item)
    except wikipedia.exceptions.PageError:
        #if a "PageError" was raised, ignore it and continue to next link
        #print "cannot make sure"
        continue
    except wikipedia.exceptions.DisambiguationError:
        #print "cannot make sure"
        continue

And I got error after several iterations. Here is the error:
1698/32256Traceback (most recent call last):
  File "/export/home/jli/PycharmProjects/practical/data_process/base_on_distance_rate.py", line 47, in <module>
    item_first = wikipedia.page(item[0])
  File "/export/home/jli/.local/lib/python2.7/site-packages/wikipedia/wikipedia.py", line 276, in page
    return WikipediaPage(title, redirect=redirect, preload=preload)
  File "/export/home/jli/.local/lib/python2.7/site-packages/wikipedia/wikipedia.py", line 299, in __init__
    self.__load(redirect=redirect, preload=preload)
  File "/export/home/jli/.local/lib/python2.7/site-packages/wikipedia/wikipedia.py", line 336, in __load
    request = _wiki_request(query_params)
  File "/export/home/jli/.local/lib/python2.7/site-packages/wikipedia/wikipedia.py", line 737, in _wiki_request
    r = requests.get(API_URL, params=params, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='en.wikipedia.org', port=443): Max retries exceeded with url: /w/api.php?inprop=url&redirects=&format=json&ppprop=disambiguation&prop=info%7Cpageprops&titles=Andrea+del+Sarto&action=query (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3666d97350>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

Could you please help me? Do you know why it happens?

**Comment by goldsmith** [comment]
you probably don't have internet!

**Comment by happyjin** [comment]
Hi, Thanks for your reply. I've already solved that. Actually I have an Internet. I just let routine sleep for 3 seconds when I call wikipedia method :)

**Comment by AmineXSaid** [comment]
> Hi, Thanks for your reply. I've already solved that. Actually I have an Internet. I just let routine sleep for 3 seconds when I call wikipedia method :)

how ?
