### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by Dalalghamdi** [goldsmith/Wikipedia#154]
Hi :) 

I wrote a script to fitch list of items definitions and there links from Wikipedia, so basically the script was working fine.. but suddenly I started to get Error 54 Connection reset by beer.. I am woundring what could be the issue, the script is 100% working, I used it several times with different lists 

here is the Traceback and the error

Traceback (most recent call last):
  File "Wiki.py", line 41, in <module>
    page = wikipedia.page(item)
  File "/Library/Python/2.7/site-packages/wikipedia/wikipedia.py", line 270, in page
    results, suggestion = search(title, results=1, suggestion=True)
  File "/Library/Python/2.7/site-packages/wikipedia/util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/wikipedia/wikipedia.py", line 103, in search
    raw_results = _wiki_request(search_params)
  File "/Library/Python/2.7/site-packages/wikipedia/wikipedia.py", line 737, in _wiki_request
    r = requests.get(API_URL, params=params, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (c))

Thanks,
Dalia

**Comment by lbbc1117** [comment]
change `wikipedia.API_URL`  from 'http://***' to 'https://***'
that's how I solved this problem
