### ISSUE TITLE
Search Issue

### ISSUE THREAD

**Issue by rohilbansal** [goldsmith/Wikipedia#162]
wikipedia.exceptions.WikipediaException: An unknown error occured: "The "search" parameter must be set.". Please report it on GitHub!

**Comment by wbchilds** [comment]
Hey @rohilbansal are you able to provide the relevant parts of your code that produce this error?

**Comment by Hardking** [comment]
got the same problem. i have simply the following code, using an anaconda environment:

wikipedia.set_lang("de")
search = 'Amerikanische Wald- und Strombilder. Erster Band. by Friedrich Gerstäcker'
content = wikipedia.page(wikipedia.search(search)).content

and i get the same error as written above

**Comment by wbchilds** [comment]
Looks like it might be problem with encoding. I can replicate your error @Hardking but only for queries with umlauts. For example, the following works fine:

```import wikipedia
wikipedia.set_lang("de")
search = 'Analogrechner'
content = wikipedia.page(wikipedia.search(search)).content
```

Returns fine. But using your query:

`search = 'Amerikanische Wald- und Strombilder. Erster Band. by Friedrich Gerstäcker'`

Yields:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\wikipedia\wikipedia.py", line 270, in page
    results, suggestion = search(title, results=1, suggestion=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wikipedia\util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wikipedia\wikipedia.py", line 109, in search
    raise WikipediaException(raw_results['error']['info'])
wikipedia.exceptions.WikipediaException: An unknown error occured: "The "search" parameter must be set.". Please report it on GitHub!
```

I'm happy to take a look into this.

Environment:
```
Windows-10-10.0.14393-SP0
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
BeautifulSoup 4.6.0
Requests 2.14.2
Wikipedia (1, 4, 0)
```
