### ISSUE TITLE
 Unicode URI  wikipedia.exceptions.PageError: Page id does not match any pages. Try another id

### ISSUE THREAD

**Issue by msj2** [goldsmith/Wikipedia#190]
Hi,
I'm on python 2.7 Ubuntu

I am trying to open a valid wiki page https://hi.wikipedia.org/wiki/%E0%A4%A8%E0%A4%AE%E0%A4%95_%E0%A4%B9%E0%A4%B2%E0%A4%BE%E0%A4%B2_(1982_%E0%A4%AB%E0%A4%BC%E0%A4%BF%E0%A4%B2%E0%A5%8D%E0%A4%AE)

as below
`# encoding=utf-8
import wikipedia
om1 = wikipedia.page("https://hi.wikipedia.org/wiki/%E0%A4%A8%E0%A4%AE%E0%A4%95_%E0%A4%B9%E0%A4%B2%E0%A4%BE%E0%A4%B2_(1982_%E0%A4%AB%E0%A4%BC%E0%A4%BF%E0%A4%B2%E0%A5%8D%E0%A4%AE")
`

I am getting error, .. 

Traceback (most recent call last):
  File "test_wikipedia_pip.py", line 3, in <module>
    om1 = wikipedia.page("https://hi.wikipedia.org/wiki/%E0%A4%A8%E0%A4%AE%E0%A4%95_%E0%A4%B9%E0%A4%B2%E0%A4%BE%E0%A4%B2_(1982_%E0%A4%AB%E0%A4%BC%E0%A4%BF%E0%A4%B2%E0%A5%8D%E0%A4%AE")
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 275, in page
    raise PageError(title)
wikipedia.exceptions.PageError: Page id "https://hi.wikipedia.org/wiki/%E0%A4%A8%E0%A4%AE%E0%A4%95_%E0%A4%B9%E0%A4%B2%E0%A4%BE%E0%A4%B2_(1982_%E0%A4%AB%E0%A4%BC%E0%A4%BF%E0%A4%B2%E0%A5%8D%E0%A4%AE" does not match any pages. Try another id!

help me.

**Comment by laundmo** [comment]
as far as i know youre not supposed to pass a URL into wikipedia.page()

try removing hhtps://hi.wikipedia.org/wiki/ and only use the characters after that

**Comment by msj2** [comment]
Thanks Laundmo forswift response.

Tried it Sir, I wasn't even to get past the 
PageError: PageError()  

I did try as below, 
`
try:
	lnk = wikipedia.page("%E0%A4%A8%E0%A4%AE%E0%A4%95_%E0%A4%B9%E0%A4%B2%E0%A4%BE%E0%A4%B2_(1982_%E0%A4%AB%E0%A4%BC%E0%A4%BF%E0%A4%B2%E0%A5%8D%E0%A4%AE")
except PageError as e:	
	print e, type(e)

`
NameError: "name 'PageError' is not defined"


Hence, I was fiddling with pass entire URL.

**Comment by martin-majlis** [comment]
@msj2 : If you can use Python 3, you can try to to use [Wikipedia-API](https://github.com/martin-majlis/Wikipedia-API). It suports page names encoded for URL.

```
w = wikipediaapi.Wikipedia('hi')

p_encoded = w.page(
    title='%E0%A4%AA%E0%A4%BE%E0%A4%87%E0%A4%A5%E0%A4%A8',
    unquote=True,
)
print(p_encoded.summary)

p_decoded = w.page(
    title='पाइथन'
)
print(p_decoded.summary)
```
