### ISSUE TITLE
DisambiguationError for an actual page in French 

### ISSUE THREAD

**Issue by nicolashernandez** [goldsmith/Wikipedia#201]
Thanks for this module (installed by pip3 in ubuntu 18.04).
 
I got a DisambiguationError for an existing page in French Wikipedia (https://fr.wikipedia.org/wiki/Inf%C3%A9rence). 

How to force the choice? The fist one ? And get a page?

Thanks

Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wikipedia
>>> wikipedia.set_lang("fr")
>>> wikipedia.page("Inférence")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/wikipedia/wikipedia.py", line 276, in page
    return WikipediaPage(title, redirect=redirect, preload=preload)
  File "/usr/local/lib/python3.6/dist-packages/wikipedia/wikipedia.py", line 299, in __init__
    self.__load(redirect=redirect, preload=preload)
  File "/usr/local/lib/python3.6/dist-packages/wikipedia/wikipedia.py", line 393, in __load
    raise DisambiguationError(getattr(self, 'title', page['title']), may_refer_to)
wikipedia.exceptions.DisambiguationError: "Inférence" may refer to: 
inférence
↑
↑
>>>

**Comment by nicolashernandez** [comment]
I should have read the documentation but... it does not solve my issue.

I catched the exception and got the alternatives
try:
  p = wikipedia.page("Inférence") 
except wikipedia.exceptions.DisambiguationError as e:
  print (e.options)
['inférence', '↑', '↑']

I tried to get the wikipedia page corresponding to the first option and got the same error.

I manually retrieved the pageid (the current module does not offer the way to do it, does it?). And attempt to get the page with the pageid. It fails again. I don t understand why and how to eventually get the required page which exists !
 
https://fr.wikipedia.org/w/api.php?action=query&titles=Inf%C3%A9rence

{
    "batchcomplete": "",
    "query": {
        "pages": {
            "11668241": {
                "pageid": 11668241,
                "ns": 0,
                "title": "Inf\u00e9rence"
            }
        }
    }
}

wikipedia.page(pageid:"11668241")

>>> wikipedia.page(pageid="11668241")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/wikipedia/wikipedia.py", line 278, in page
    return WikipediaPage(pageid=pageid, preload=preload)
  File "/usr/local/lib/python3.6/dist-packages/wikipedia/wikipedia.py", line 299, in __init__
    self.__load(redirect=redirect, preload=preload)
  File "/usr/local/lib/python3.6/dist-packages/wikipedia/wikipedia.py", line 393, in __load
    raise DisambiguationError(getattr(self, 'title', page['title']), may_refer_to)
wikipedia.exceptions.DisambiguationError: "Inférence" may refer to: 
inférence
↑
↑
