### ISSUE TITLE
KeyError: u'extlinks' when using preload=True in page()

### ISSUE THREAD

**Issue by Clam-** [goldsmith/Wikipedia#78]
```
>>> wikipedia.page("747", preload=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\wikipedia\wikipedia.py", line 276, in page
    return WikipediaPage(title, redirect=redirect, preload=preload)
  File "c:\Python27\lib\site-packages\wikipedia\wikipedia.py", line 303, in __init__
    getattr(self, prop)
  File "c:\Python27\lib\site-packages\wikipedia\wikipedia.py", line 592, in references
    'ellimit': 'max'
  File "c:\Python27\lib\site-packages\wikipedia\wikipedia.py", line 423, in __continued_query
    for datum in pages[self.pageid][prop]:
KeyError: u'extlinks'
>>> wikipedia.__version__
(1, 4, 0)
```

**Comment by DancingQuanta** [comment]
I got the same thing too

**Comment by DancingQuanta** [comment]
I found that if a page have references with no link, this error occurs.

**Comment by ramusus** [comment]
Here is another way to reproduce the bug using python3:

```
In [3]: import wikipedia
In [4]: wikipedia.set_lang('ru')
In [5]: wikipedia.page('Дворецкий Боб').references
....
KeyError: 'extlinks'
```
