### ISSUE TITLE
wikipedia.exceptions.WikipediaException: An unknown error occured

### ISSUE THREAD

**Issue by garzai** [goldsmith/Wikipedia#96]
Running this code ( http://pastebin.com/RLErTXW2 ), I got this error traceback:

Traceback (most recent call last):
      File "/home/pharoslabsllc/Documents/test/code_testing.py", line 47, in <module>
        add_section_info(line)
      File "/home/pharoslabsllc/Documents/test/code_testing.py", line 24, in add_section_info
        toc = wp.page(search).sections
      File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 270, in page
        results, suggestion = search(title, results=1, suggestion=True)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 109, in search
    raise WikipediaException(raw_results['error']['info'])
wikipedia.exceptions.WikipediaException: An unknown error occured: "text search is disabled". Please report it on GitHub!
[Finished in 12.6s with exit code 1]
[shell_cmd: python -u "/home/pharoslabsllc/Documents/test/code_testing.py"]
[dir: /home/pharoslabsllc/Documents/test]
[path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]

**Comment by wacax** [comment]
I got the same issue. I queried it with the following, 
wikiArticle = wikipedia.page("    Motion (physics)") #spaces at the beginning

and I got the following

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2820, in run_code
    exec code_obj in self.user_global_ns, self.user_ns
  File "<ipython-input-3-aa5feac20c44>", line 41, in <module>
    wikiArticle = wikipedia.page(article.lower())
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 270, in page
    results, suggestion = search(title, results=1, suggestion=True)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 109, in search
    raise WikipediaException(raw_results['error']['info'])
WikipediaException: An unknown error occured: "text search is disabled". Please report it on GitHub!

**Comment by jonscyriac** [comment]
is there any progress on this?
 wikipage = wiki.page(title=title) File "/usr/local/lib/python3.5/site-packages/wikipedia/wikipedia.py", line 270, in page results, suggestion = search(title, results=1, suggestion=True) File "/usr/local/lib/python3.5/site-packages/wikipedia/util.py", line 28, in __call__ ret = self._cache[key] = self.fn(*args, **kwargs) File "/usr/local/lib/python3.5/site-packages/wikipedia/wikipedia.py", line 109, in search raise WikipediaException(raw_results['error']['info']) wikipedia.exceptions.WikipediaException: An unknown error occured: "We could not complete your search due to a temporary problem. Please try again later.". Please report it on GitHub!

**Comment by jonscyriac** [comment]
The problem would be your search string. for example, i had a .page() string with 'OR' in it. Wikipedia would probably have thrown some internal error thinking it would be an instruction.The remedy is to convert the string to lower case before .page(). As it turns out the case wont affect the result.
